/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KirkpatrickSeidelImport } from './routes/kirkpatrick-seidel'
import { Route as JarvisMarchImport } from './routes/jarvis-march'
import { Route as AnalysisImport } from './routes/analysis'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const KirkpatrickSeidelRoute = KirkpatrickSeidelImport.update({
  path: '/kirkpatrick-seidel',
  getParentRoute: () => rootRoute,
} as any)

const JarvisMarchRoute = JarvisMarchImport.update({
  path: '/jarvis-march',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisRoute = AnalysisImport.update({
  path: '/analysis',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/analysis': {
      preLoaderRoute: typeof AnalysisImport
      parentRoute: typeof rootRoute
    }
    '/jarvis-march': {
      preLoaderRoute: typeof JarvisMarchImport
      parentRoute: typeof rootRoute
    }
    '/kirkpatrick-seidel': {
      preLoaderRoute: typeof KirkpatrickSeidelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  AnalysisRoute,
  JarvisMarchRoute,
  KirkpatrickSeidelRoute,
])

/* prettier-ignore-end */
